moved error sim up

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -7,6 +7,9 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
       - name: Checkout 🛎️
         uses: actions/checkout@v2
         with:
@@ -23,8 +26,3 @@ jobs:
 
       - name: Test 🚨
         run: npm test
-
-      - name: Simulate an error
-        run: echo "About to fail" ; exit 1
-
-      # comment
