changes to whatever

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -23,3 +23,8 @@ jobs:
 
       - name: Test 🚨
         run: npm test
+
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
+      # comment
